# Generated by Django 6.1 on 2026-08-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kn', models.CharField(help_text='Kannada category name', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Package', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_kn', models.CharField(help_text='Kannada product name', max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('crop_usage', models.CharField(help_text='e.g. Cotton, Jowar, Soybean, Chilli', max_length=255)),
                ('rating', models.FloatField(default=4.5)),
                ('active', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_instructions', models.TextField(help_text='Step by step application instructions')),
                ('dosage', models.CharField(help_text='e.g. 2-3 g per liter of water', max_length=255)),
                ('timing', models.CharField(help_text='e.g. Early morning or late evening', max_length=255)),
                ('sunny_guidance', models.CharField(default='Ideal for spraying. Apply in early morning before high temperatures.', max_length=255)),
                ('rainy_guidance', models.CharField(default='Do not apply if heavy rain is expected within 4 hours.', max_length=255)),
                ('windy_guidance', models.CharField(default='Avoid spraying in high wind to prevent drift to neighboring crops.', max_length=255)),
                ('cold_guidance', models.CharField(default='Store in warm dry place. Ensure thorough mixing before application.', max_length=255)),
                ('precautions', models.TextField(help_text='Safety equipment and precautions')),
                ('storage', models.TextField(help_text='Storage requirements')),
                ('safety_warning', models.TextField(default='Use only according to the product label and applicable agricultural guidance. Do not exceed the recommended dosage.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideline', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='e.g. 1 KG, 5 KG, 25 KG, 500 ML, 1 L', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0, help_text='Discount percentage')),
                ('stock', models.IntegerField(default=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
